### ISSUE TITLE
Request: Allow reading partial data

### ISSUE THREAD

**Issue by jcmnn** [holmesv3/sicd-rs#13]
SICD files are frequently large (2+ GB) and take a lot of memory to read into memory all at once. It would be useful to have a way to load a window of data. E.g. sarpy does not load data when opening the SICD, but only after calling sicd.read() or sicd.read(window).

**Comment by holmesv3** [comment]
Good afternoon - thanks for the input! 

I've played around with this a little bit already and it shouldn't be too bad, there are just a few quirks to figure out.

I'll start working on this again. If you have any suggestions or want to take a crack at it yourself, feel free to!

**Comment by holmesv3** [comment]
I have a branch up with an initial version of this. I still need to do some work on the docs and make sure it's doing what I think it is.

The sicd specifies data must be encoded big-endian, hence a 'native' `[f32; 2]` or `Complex32` can't be used. 

There is a `zerocopy` crate which provides endian-ness specifications, so I made an `ArrayView2` of that big-endian f32, which makes it so that you should be read any data 'for free' since you're just making references to a memory map. (I'm not 100% sure on this yet, will verify with some large files this week)

I also made a little convenience trait which can take that array of the zerocopy `F32<BE>` type and convert it to an owned `Complex<f32>` 'native' version (this does allocation). Not sure if that's really going to be useful or not.

**Comment by holmesv3** [comment]
I tested this today. I was able to read a file that was over 100GB, and reference all of the image segment data through the `ArrayView`'s provided by the `ImageData` vector on the `Sicd` object. 

I verified that several slices out of the arrays matched what `sarpy` read from the same slices.

**Comment by jcmnn** [comment]
Awesome! I'll try it out later, thanks for the quick response
